# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# initialize the spacy configurations 
 
 - name: SpacyNLP
   model: dataset/spacy.word2vec.model
 # used to create tokens on the basis of the whitespace e.g. => how are you ? =conversion> tokensList=>["how","are","you","?"]
 - name: SpacyTokenizer
 # used to vector representation of user message or features for entity extraction, intent classification, and response classification using the spaCy featurizer.
 - name: SpacyFeaturizer
 - name: LanguageModelFeaturizer
   model_name: bert
   model_weights: "rasa/LaBSE"
 # Creates features for entity extraction and intent classification. During training the RegexFeaturizer creates a list of regular expressions defined in the training data format
 - name: RegexFeaturizer
# used to map synonym of entity. 
 - name: EntitySynonymMapper
 # Dual Intent Entity Transformer (DIET) used for intent classification and entity extraction
 - name: DIETClassifier
   epochs: 200
   random_seed: 2
#  - name: CRFEntityExtractor
#  - name: SklearnIntentClassifier
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
